# Generated by Django 4.0 on 2025-07-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment1',
            new_name='Appointment',
        ),
    ]
