# Generated by Django 5.2.3 on 2025-07-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='fulltname',
            new_name='fullname',
        ),
    ]
