# Generated by Django 5.2.3 on 2025-07-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_fulltname_doctors_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Capacity', models.IntegerField()),
                ('Department', models.CharField(max_length=100)),
                ('Floor', models.IntegerField()),
            ],
        ),
    ]
