# Generated by Django 5.2.3 on 2025-07-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='department',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
